# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Song.create(artist: 'Michael Jackson', title: "Billie Jean", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png', audio:'audio1')
Song.create(artist: 'Michael Jackson', title: "Thriller", genre: "pop", image:'https://3.bp.blogspot.com/_mupIVJbjvuU/TIhkKUDzboI/AAAAAAAAGuc/lUPLncxSINo/s1600/Michael+Jackson+-+Thriller+(FanMade+Single+Cover)+Made+by+JasonCoverz.png', audio:'audio2')
Song.create(artist: 'Michael Jackson', title: "Smooth Criminal", genre: "pop", image:'https://d2tml28x3t0b85.cloudfront.net/tracks/artwork/01212490358211e8a4f333cbe1c96a8c/01b638a0358211e880fe29a4fc03d8de-15050461_1161295003948835_1830086473_n.jpg', audio:'audio1')
Song.create(artist: 'Beyoncé', title: "Halo", genre: "pop", image:'https://i.pinimg.com/originals/5a/b7/8e/5ab78e04f135786e052375321956e43e.jpg', audio:'audio3')
Song.create(artist: 'Beyoncé', title: "Single Ladies", genre: "pop", image:'https://i.pinimg.com/originals/5a/b7/8e/5ab78e04f135786e052375321956e43e.jpg', audio:'audio4')
Song.create(artist: 'Camila Cabello', title: "Havana", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/9/98/Havana_%28featuring_Young_Thug%29_%28Official_Single_Cover%29_by_Camila_Cabello.png', audio:'audio5')
Song.create(artist: 'Camila Cabello', title: "Señorita", genre: "pop", image:'https://vignette.wikia.nocookie.net/karlacamilacabello/images/1/16/Unreleased-1.jpg/revision/latest?cb=20191208034755', audio:'audio6')
Song.create(artist: 'Ariana Grande', title: "Thank U, Next", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/4/4b/Ariana_Grande_-_Dangerous_Woman_%28Official_Album_Cover%29.png', audio:'audio7')
Song.create(artist: 'Ariana Grande', title: "Break Up with Your Girlfriend, I'm Bored", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/4/4b/Ariana_Grande_-_Dangerous_Woman_%28Official_Album_Cover%29.png', audio:'audio8')
Song.create(artist: 'Ariana Grande', title: "Side to Side", genre: "pop", image:'https://i.pinimg.com/originals/7b/f2/f8/7bf2f85c5a9b56968bdd9b5fb25beb6a.jpg', audio:'audio9')
Song.create(artist: 'Ariana Grande', title: "Focus", genre: "pop", image:'https://i.pinimg.com/originals/7b/f2/f8/7bf2f85c5a9b56968bdd9b5fb25beb6a.jpg', audio:'audio10')
Song.create(artist: 'Ariana Grande', title: "The Way", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/4/4b/Ariana_Grande_-_Dangerous_Woman_%28Official_Album_Cover%29.png', audio:'audio11')
Song.create(artist: 'Billie Eilish', title: "Bad Guy", genre: "pop", image:'https://www.music-bazaar.com/album-images/vol32/2232/2232485/4110464-big/Singles-Rarities-Remixes-Unofficial-Yellow-cover.jp', audio:'audio12')
Song.create(artist: 'Billie Eilish', title: "When the party is over", genre: "pop", image:'https://www.music-bazaar.com/album-images/vol32/2232/2232485/4110464-big/Singles-Rarities-Remixes-Unofficial-Yellow-cover.jp', audio:'audio13')
Song.create(artist: 'Billie Eilish', title: "Lovely", genre: "pop", image:'https://www.music-bazaar.com/album-images/vol32/2232/2232485/4110464-big/Singles-Rarities-Remixes-Unofficial-Yellow-cover.jp', audio:'audio14')
Song.create(artist: 'Taylor Swift', title: "Love Story", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/c/cd/Taylor_Swift_-_Lover.png', audio:'audio15')
Song.create(artist: 'Taylor Swift', title: "Shake it Off", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/c/cd/Taylor_Swift_-_Lover.png', audio:'audio16')
Song.create(artist: 'Taylor Swift', title: "Blank Space", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/c/cd/Taylor_Swift_-_Lover.png', audio:'audio17')
Song.create(artist: 'Post Malone', title: "Congradulations", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/thumb/1/15/DejaVuPostMalone.jpg/220px-DejaVuPostMalone.jpg', audio:'audio18')
Song.create(artist: 'Post Malone', title: "Sunflower", genre: "pop", image:'https://upload.wikimedia.org/wikipedia/en/thumb/1/15/DejaVuPostMalone.jpg/220px-DejaVuPostMalone.jpg', audio:'audio19')

User.create(username: Faker::Internet.username)
User.create(username: Faker::Internet.username)
User.create(username: Faker::Internet.username)
User.create(username: Faker::Internet.username)
User.create(username: Faker::Internet.username)
User.create(username: Faker::Internet.username)


Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)
Favorite.create(user_id: User.all.sample.id, song_id: Song.all.sample.id)

